seed: 3431
project_name: "baseline"
run_name: "test"
tokenizer_name: "klue/roberta-large"
model_name: "klue/roberta-large"
num_labels: 30
    
train_data_path: "../data/fixed_dev_dataset.csv"
validation_data_path: "../data/fixed_dev_dataset.csv"
test_data_path: "../data/test/test_data.csv"

label_to_num_dict_path: "../data/dict_label_to_num.pkl"
num_to_label_dict_path: "../data/dict_num_to_label.pkl"
submission_path: "../data/sample_submission.csv"

data_dir: "../data/"
save_dir: "saved"
wandb_dir: "wandb_checkpoints"
submission_dir: "submissions"

max_epoch: 5
batch_size: 32
max_length: 256
shuffle: True
validation_split: 0.1
num_workers: 4
lr: 1e-5

## kfold
num_folds: 5